FROM alpine:latest

ARG UID
ARG GID
RUN addgroup -g ${GID} -S mpd && adduser --uid ${UID} -S -G mpd mpd

RUN apk update && \
    apk add mpd 

VOLUME /music
VOLUME /mpd

CMD ["mpd", "--stdout", "--no-daemon", "/etc/mpd.conf"]
