version: '3.8'
services:
  icecast:
    user: icecast
    image: infiniteproject/icecast
    ports:
      - "8000:8000"
    volumes:
      - ./icecast.xml:/etc/icecast.xml
      - ./music:/music
      - ./jingles:/usr/share/icecast/web/jingles
      - ./logs/icecast:/var/log/icecast
  mpd-voice:
    user: mpd
    build:
      context: .
      dockerfile: Dockerfile.voice.mpd
    image: irirangi-mpd-voice-image:latest
    volumes:
      - ./mpd.voice.conf:/etc/mpd.conf
      - ./voice:/voice
      - ./mpd:/mpd

  mpd:
    user: mpd
    build:
      context: .
      dockerfile: Dockerfile.music.mpd
    image: irirangi-mpd-image:latest
    volumes:
      - ./mpd/run/:/run/mpd/
      - ./mpd.music.conf:/etc/mpd.conf
      - ./music:/music
      - ./mpd:/mpd

  bot:
    build:
      context: .
      dockerfile: Dockerfile.py.bot
    image: irirangi-telegram-bot:latest
    volumes:
      - ./music:/music
      - ./voice:/voice
      - ./app:/app
    command: /bin/sh -c "sleep 2 && python /app/bot.py"
    restart: unless-stopped
