FROM alpine:latest

ARG UID
ARG GID

RUN addgroup -g ${GID} -S mpd && adduser --uid ${UID} -S -G mpd mpd

RUN apk update && \
    apk add mpd 

RUN mkdir -p /music
RUN mkdir -p /mpd/db
RUN mkdir -p /mpd/playlists

RUN chown -R mpd:mpd /mpd
RUN chown -R mpd:mpd /music

VOLUME /music
VOLUME /mpd

USER mpd
CMD ["mpd", "--stderr", "--no-daemon", "/etc/mpd.conf"]
