version: '3.8'                   
services:
  icecast:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile.voice.mpd
    image: irirangi-icecast-image
    ports:
      - "8000:8000"
    volumes:
      - ./icecast.xml:/etc/icecast.xml
      - ./music:/music
      - ./jingles:/usr/share/icecast/web/jingles
  mpd-voice:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile.voice.mpd
    image: irirangi-mpd-voice-image
    volumes:
      - ./mpd.voice.conf:/etc/mpd.conf
      - ./voice:/voice
      - ./mpd:/mpd

  mpd:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile.music.mpd
    image: irirangi-mpd-image
    volumes:
      - ./mpd/run/:/run/mpd/
      - ./mpd.music.conf:/etc/mpd.conf
      - ./music:/music
      - ./mpd:/mpd

  bot:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile.py.bot
    image: irirangi-telegram-bot
    env_file:
      - bot.env
    volumes:
      - ./music:/music
      - ./voice:/voice
      - ./app:/app
    restart: unless-stopped
