FROM python:3.9-alpine

ARG UID
ARG GID

RUN addgroup -g ${GID} -S bot && adduser --uid ${UID} -S -G bot bot

WORKDIR /app

COPY requirements.txt .

RUN apk add --no-cache --virtual .build-deps \
        gcc \
        musl-dev \
        libffi-dev \
        openssl-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps
RUN apk add mpc ffmpeg
RUN apk add mp3gain --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/

USER bot

CMD ["python", "bot.py"]
